### ISSUE TITLE
[DMP 2024]: 

### ISSUE THREAD

**Issue by a2i-dpg** [a2i-code-For-Govstack/task-manager#1]
## Description
A Task Manager is a platform for managing task, subtask & events for users. It offers a user-friendly interface to maintain the task, subtask & events. This platform also offers single and recurring event setup with calendar sharing mechanism. Facilitate users to set their meeting/event time in the calendar as well as sharing with the team/office/external offices. Assigned in task, subtask & events other officers and ensure necessary notifications. User will have the access to communicate though real time chat or task comment with other team mates about the tasks. Overall, this Task Manager platform provides a comprehensive solution for users to efficiently manage their tasks, schedule events, collaborate with team members, and stay organized with timely notifications and communication tools.

### New feature Development Scope:
1. Add event directly in Google Calendar
2. Integration with Notification service
3. Login through SSO 
4. Enhance UI/UX

## Goals
Goals for Task Manager:

- [x] User-Friendly Interface: Develop an intuitive and user-friendly design for easy task & event management.
- [x] Enhance Productivity: To enhance productivity by providing users with tools and features to efficiently manage their tasks, prioritize work, and meet deadlines.
- [x] Improve Organization: The platform should help users stay organized by providing a centralized location to create, track, and manage tasks, subtasks, and events. It should offer intuitive categorization and filtering options for better organization.
- [x] Facilitate Collaboration: Enable seamless collaboration among team members by allowing them to assign tasks, share calendars, communicate through real-time chat or comments, and work together on projects.
- [x] Increase Accountability: By enabling users to assign tasks to specific individuals, track progress, and receive notifications about upcoming deadlines or overdue tasks.
- [x] Streamline Communication: Provide communication tools such as real-time chat/ task comments to facilitate efficient communication among team members, reducing the need for lengthy email threads or separate communication channels.
- [x] Ensure Security and Data Privacy: Prioritize security measures to protect sensitive data and ensure user privacy, including encryption of data, secure authentication mechanisms, and compliance with relevant data protection regulations.

### Milestones for a Task Manager:

- [x] Prototype Development: Create an initial version showcasing basic task manager functionalities.
- [x] User Testing: Gather feedback from users to refine and improve the task manager usability.
- [x] Official Release: Launch the task manager to the public, marking its availability for organizations employee use with authentication policy.

### Setup/Installation

##SETUP :

composer update

composer install

cp .env.example .env

php artisan key:generate

composer require laravel/passport

php artisan passport:install

php artisan migrate

## Cache Clear
php artisan config:cache

### Expected Outcome

make the product as Plug and Playable , more inntegratable and user friendly

### Acceptance Criteria

make the product as Plug and Playable , more inntegratable and user friendly

### Implementation Details

laravel

### Mockups/Wireframes

n/a

### Product Name

Task Manager

### Organisation Name

a2i

### Domain

⁠Service Delivery

### Tech Skills Needed

Bootstrap, Database, Design, HTML, JavaScript, Laravel, Material-UI, SQL, Test, UI/UX/Design, Other

### Mentor(s)

[a2i ](https://github.com/a2i-dpg) , [mahmud ](https://github.com/theeMahmud) , [Farhad](https://github.com/nbfarhad) ,[nahin ](https://github.com/NahinAhmed28) , [sanaullah ](https://github.com/ringku369)

### Category

API, Analytics, Accessibility, Backend, Beginner Friendly, Database, Frontend, Other

**Comment by SanjanaSogimatt** [comment]
@a2i-dpg Can I work on this?

**Comment by r4ravikumar-dev** [comment]
@a2i-dpg I'm a ux designer can I work on this?

**Comment by AnuragRoshan** [comment]
can we use other other backend framework or database ?

**Comment by Danishyousuf19** [comment]
Can i work  on ui ux design

**Comment by jaymehta002** [comment]
Can i work on this?
i am a full stack developer with experience in UI/UX designing

**Comment by yashpatel139** [comment]
hey @a2i-dpg I'm interested in this project . Can i work on this project?

**Comment by ghost** [comment]
@a2i-dpg 
I hope this message finds you well. I'm a student in my 4th year pursuing CSE. I have an honors score in Full Stack Development using PHP with Laravel framework. I have built a Task Manager before but with a very simple base using the same tech stack which was my honors degree project in my 2nd year. Here is the link - https://github.com/sakshi-sonii/Task-Manager---LARAVEL. I'm interested in working on this project and achieve the milestones with improved functionalities and design. May I work on this project ?

**Comment by Vin205** [comment]
I have experience in UI/UX designing and have all skills in frontend web development, can I work on this  project

**Comment by a2i-dpg** [comment]
> Can i work on ui ux design

Hi . Do you also want to contribute on the coding implementation ?

**Comment by a2i-dpg** [comment]
> Hi . Do you also want to contribute on the coding implementation ?

Hi . Do you also want to contribute on the coding implementation ?

**Comment by a2i-dpg** [comment]
> @a2i-dpg I hope this message finds you well. I'm a student in my 4th year pursuing CSE. I have an honors score in Full Stack Development using PHP with Laravel framework. I have built a Task Manager before but with a very simple base using the same tech stack which was my honors degree project in my 2nd year. Here is the link - https://github.com/sakshi-sonii/Task-Manager---LARAVEL. I'm interested in working on this project and achieve the milestones with improved functionalities and design. May I work on this project ?

Can you please specify on your vision and target on the features updates ? Please also mention the features you would like to work on.

**Comment by a2i-dpg** [comment]
> Can you please specify on your vision and target on the features updates ? Please also mention the features you would like to work on.

Can you please specify on your vision and target on the features updates ? Please also mention the features you would like to work on.

**Comment by a2i-dpg** [comment]
> can we use other other backend framework or database ?

Which Backend framework are you suggesting ?

**Comment by a2i-dpg** [comment]
> @a2i-dpg Can I work on this?

Can you please specify on your vision and target on the features updates ? Please also mention the features you would like to work on.

**Comment by ghost** [comment]
> > @a2i-dpg I hope this message finds you well. I'm a student in my 4th year pursuing CSE. I have an honors score in Full Stack Development using PHP with Laravel framework. I have built a Task Manager before but with a very simple base using the same tech stack which was my honors degree project in my 2nd year. Here is the link - https://github.com/sakshi-sonii/Task-Manager---LARAVEL. I'm interested in working on this project and achieve the milestones with improved functionalities and design. May I work on this project ?
> 
> Can you please specify on your vision and target on the features updates ? Please also mention the features you would like to work on.

Hello @a2i-dpg ,

Thank you for considering my interest in contributing to your Task Manager project. I appreciate the opportunity to discuss my vision and target for the feature updates.

My vision for the project is to enhance the Task Manager platform by focusing on improving user experienceand increasing functionality for task and event management.

Specifically, I would like to work on the following features:

1. Google Calendar Integration: Enable users to seamlessly add events from the Task Manager directly to their Google Calendar, enhancing productivity and synchronization across platforms.

2. UI/UX Enhancements: Improve the user interface and experience by redesigning key elements to make the platform more intuitive and visually appealing, ultimately enhancing user engagement and satisfaction.

3. All basic and advanced features that a task manager or an event manager should have.

I am committed to working closely with you and the team to ensure that these features are implemented effectively and align with the project's objectives. Please let me know if you have any further questions or if there are additional features you would like to prioritize.

Looking forward to your feedback.

Also, I submitted my proposal on the registration site and also attached the proposal file here
[Proposal Template DMP 2024.pdf](https://github.com/a2i-code-For-Govstack/task-manager/files/14975160/Proposal.Template.DMP.2024.pdf)

Best regards,
Sakshi soni

**Comment by AbhimanyuSamagra** [comment]
Do not ask process related questions about how to apply and who to contact in the above ticket. The only questions allowed are about technical aspects of the project itself. If you want help with the process, you can refer instructions listed on [Unstop](https://unstop.com/competitions/dedicated-mentoring-program-dmp-2024-code-for-govtech-932803?lb=7gWXVfKv) and any further queries can be taken up on our [Discord channel](https://discord.com/invite/VPrXf7Jxpr) titled DMP queries. Here's a [Video Tutorial](https://youtu.be/nMW-nD8WzHY) on how to submit a proposal for a project.

**Comment by Riyasharma28** [comment]
Respected Mentor @a2i-dpg 
I'm a Full Stack Developer proficient in HTML, CSS, JavaScript, MongoDB, React.js, Node.js, Bootstrap, Database Management, UI/UX Design, Test-driven Development, and frameworks like  Material-UI. With over 10 projects completed in similar domains, I'm eager to contribute my expertise to your project. I'm excited about the opportunity to collaborate and drive its success. Looking forward to discussing this further.

**Comment by mridulsaggi** [comment]
Hi @a2i-dpg , i am mridul, a full stack MERN developer with 3+years of experience in Open source contribution. I carefully went through the project requirements and wanted to work on this project starting from the redesigning the UI of the website to make it user friendly for better implementation, and creating the features such as direct adding the task in google calendrer, creating friendly reminder of tasks, a structured and graphical visualization of upcoming as well as past tasks. Looking forward to work on the project. Thankyou!

**Comment by behldevansh** [comment]
Respected Mentor @a2i-dpg 
With extensive experience in open-source development, I bring a unique blend of skills and passion to contribute meaningfully. Winning the Smart India Hackathon 2023 and receiving special mention in FinAThon further underscore my commitment to innovation and problem-solving. With proficiency in languages like Python, C/C++, and JavaScript,Typescript, along with frameworks like React and Next.js, Database and services includes Mongo DB, Appwrite, Firebase, Redis . I’m eager to leverage my skills to drive impactful contributions within the open-source community.

**Comment by Rahulkumar2488** [comment]
Respected Mentor @a2i-dpg
I'm a Web Developer Developer proficient in HTML, CSS, JavaScript, MongoDB, React.js, Node.js, Bootstrap, Database Management, UI/UX Design, Test-driven Development, and frameworks like Material-UI. With over 10 projects completed in similar domains, I'm eager to contribute my expertise to your project. I'm excited about the opportunity to collaborate and drive its success. Looking forward to discussing this further.

**Comment by Riyasharma28** [comment]
You should not copy someone's content , but surprisingly you have copied the entire tech stack also with project numbers that too openly

**Comment by Riyasharma28** [comment]
> Respected Mentor @a2i-dpg I'm a Web Developer Developer proficient in HTML, CSS, JavaScript, MongoDB, React.js, Node.js, Bootstrap, Database Management, UI/UX Design, Test-driven Development, and frameworks like Material-UI. With over 10 projects completed in similar domains, I'm eager to contribute my expertise to your project. I'm excited about the opportunity to collaborate and drive its success. Looking forward to discussing this further.

You should not copy someone's content, but surprisingly you have copied the entire tech stack also with project numbers that too openly

@a2i-dpg kindly see

**Comment by Mrunalkhanke** [comment]
**Respected Mentor @a2i-dpg** 
I am reaching out to express my interest in contributing to the Task Management project listed on  GitHub. After reviewing the project details and its tech stack, I am excited about the opportunity to collaborate and contribute to its development.
**With over 3 years of professional experience in HTML, CSS, JavaScript, and PHP and as a UI/UX designer** , I have honed my skills through the creation of numerous projects, totaling six in number. **Additionally, my freelancing experience has allowed me to work on real-time full-stack projects,** further solidifying my proficiency in these technologies. have also actively participated in various hackathons, including **Devshouse 2024, She Hacks 2024, and Smart India Hackathon,** where I had the opportunity to apply my skills to solve real-world challenges under tight deadlines.I would be grateful for the opportunity to discuss further details and explore how I can contribute to the project in alignment with your vision. Please let me know if you would be available for a discussion at your earliest convenience. 
Thank you
**mrunalkhanke7@gmail.com**

**Comment by amamisha59** [comment]
Respected Mentor @a2i-dpg,
I hope this message finds you well. I am writing to express my interest in contributing to the development of the Task Manager project. With my experience in HTML, CSS, JavaScript, Bootstrap, and a keen interest in database management, I believe I can make valuable contributions to enhance the functionality and user experience of the platform.

Here are the areas where I would like to focus my contributions:

1. To-Do List Feature: I am keen to work on developing the to-do list functionality for users. This includes designing and implementing an intuitive interface for users to create, manage, and prioritize their tasks efficiently.
2. Database Enhancement: I am eager to delve into the database aspect of the project to enhance my learning. I would like to contribute to optimizing database structures, improving data querying efficiency, and ensuring data integrity and security.
Additionally, I am excited about the goals and milestones outlined for the Task Manager project, particularly in terms of enhancing productivity, facilitating collaboration, and ensuring security and data privacy. 
I am looking forward to be one of the contributor for this project.

**Comment by kaushiksai711** [comment]
Hello Mentor @a2i-dpg,
I take this moment to thank you for this opportunity.
I would love to play a part in developing a Task Manager with various interfaces .I have experience in HTML, CSS, JavaScript, Bootstrap, node.js, react.js, and am currently working on mongo db. I believe my idea can impact user experience of the platform and make it very user friendly.

(my proposal link is at end ,please do read the whole message if possible)


Basic Idea : Turn Task manager into a Game of Stages/Levels (came to this conclusion after trying out present task managers as they are complex and not appealing even though they have all functionalities)

Note:I would like your inputs on my idea below:

I would like to emphasize my thoughts  on UI/UX enhancements and creating a fully functional chatbot, regression analysis for predictions ,leader board for competitive spirit:

1.UI UX enhancements: I want to create various themes using larvel, such as space theme ,guild hall theme ,fantasy world theme ,each theme targets different audience guild hall for organization , fantasy world for a team , and space for individual .They can be used interchange-ably. Each theme will function similar to blender(realistic 3d interface)
I have explained in detail about the themes in my proposal

2.Chatbot: This might feel additional but my intention is to reduce the strain on users by automating most of process such as creating tasks, submitting tasks ,etc  using chatbot and it will be useful for introducing task manager interface tools to users and addressing any queries.

3.Regression analysis :To predict traffic of users so that system can inform whether it needs to scale to ensure there is no overload. Can use Google analytics. 

Leader Board:
I am also planning to make a leader board for teams/organisation and rank users based on parameters like efficiency, amount of tasks completed ,time and some other factors , which can improve competitiveness and interest in website.

These are some of ideas i stated for UI/UX.

I am  eager to learn other aspects of projects such as ensuring security and data privacy.
I would give my best if i was selected as one of the contributor for this project.

(I have kept the minimum amount of time a team needs to finish  the project ,I am flexible to increase my work time if required  )

Please do view my proposal for more details
[Proposal-final.pdf](https://github.com/a2i-code-For-Govstack/task-manager/files/15252785/Proposal-final.pdf)

**Comment by abshek7** [comment]
Hello ,I am 2nd year UG student looking to dive into world of open source with little experience of projects with html,css and js in frontend and flask in backend with sqlite database . I am interested in this project Task Manager .Please do checkout my request for considering my collaboration

**Comment by ImRAJAS-SAMSE** [comment]
# Weekly Learnings & Updates (To be filled by contributor)

## Week 1
- **Learning 1**: Explored the basics of the Laravel framework, focusing on setting up a local development environment using XAMPP.
- **Learning 2**: Gained an understanding of Laravel routes and controllers, and how they interact to handle HTTP requests.
- **Learning 3**: Learned about integrating form validation in Laravel using the Validator facade.

## Week 2
- **Learning 1**: Explored the principles of UI/UX design, focusing on usability, visual hierarchy.
- **Learning 2**: Enhancing UI with CSS and JavaScript.
- **Learning 3**: Learned about responsive design.

## Week 3
- **Learning 1**: Implemented basic CRUD (Create, Read, Update, Delete) operations for tasks and events, gaining practical experience in database interactions with Laravel.
- **Learning 2**: Investigated potential enhancements for the UI by researching best practices in front-end development, focusing on user experience and responsiveness.
- **Learning 3**: Developed problem-solving skills by troubleshooting and resolving issues encountered during the implementation of CRUD functionalities.

## Week 4
- **Learning 1**: Conducted thorough testing of the implemented features, identifying and fixing bugs to ensure a stable application.
- **Learning 2**: Enhanced understanding of Laravel's testing tools and methodologies, including PHPUnit and feature testing.
- **Learning 3**: Explored additional feature implementations based on feedback and identified areas for potential improvements.

## Week 5
- **Learning 1**: Finalized all features and resolved any remaining bugs to prepare the application for the first milestone review.
- **Learning 2**: Prepared detailed documentation of the project, including user guides, technical documentation, and a presentation for the milestone review.
- **Learning 3**: Gained experience in presenting project progress and findings, focusing on clear communication and comprehensive coverage of project achievements.

## Week 6
- **Learning 1**: Gained deeper understanding of Laravel's notification system, exploring both database and email notifications.
- **Learning 2**: Implemented Laravel's built-in notification service, learning to create custom notification channels for event triggers.
- **Learning 3**: Researched various notification channels and explored how Laravel queues can be used to send notifications asynchronously.

## Week 7
- **Learning 1**: Worked on integrating email notifications, diving into third-party services like SendGrid and MailerSend.
- **Learning 2**: Configured MailerSend's API, gaining experience in handling external services within Laravel.
- **Learning 3**: Learned how to test and validate email notification features, ensuring reliable delivery and user experience.

## Week 8
- **Learning 1**: Finalized the email notification service, improving reliability and ensuring notifications were triggered for events such as create, update, or delete.
- **Learning 2**: Explored in-app notifications using Laravel's notification system to create a seamless user experience.
- **Learning 3**: Enhanced the user interface to display notifications effectively, focusing on both mobile and desktop responsiveness.

## Week 9
- **Learning 1**: Completed UI/UX improvements based on mid-point evaluation feedback, enhancing design elements like colors, fonts, and layouts.
- **Learning 2**: Improved the mobile responsiveness of the app’s UI to ensure a smooth user experience across devices.
- **Learning 3**: Conducted user experience testing, collecting feedback from test users to refine UI interactions and overall design.

## Week 10
- **Learning 1**: Focused on final UI refinements, ensuring that the application adhered to modern design principles and user accessibility standards.
- **Learning 2**: Learned about testing accessibility and performance across different devices and screen sizes.
- **Learning 3**: Documented the process of UI/UX changes, explaining the rationale behind key design decisions.

## Week 11
- **Learning 1**: Reviewed all notification service features to ensure they were functioning correctly after UI updates.
- **Learning 2**: Explored how to extend Laravel's notification system for potential future integrations with SMS or other channels.
- **Learning 3**: Practiced presenting the final UI/UX and notification service features, preparing for the project showcase.

## Week 12
- **Learning 1**: Finalized the project, focusing on polishing the UI and ensuring the application’s notification service was fully functional.
- **Learning 2**: Refined the project presentation, emphasizing the features we implemented and their value to users, particularly within the context of the government employee audience.

**Comment by abhisheksyadav05** [comment]
- [ ] *Week 1: June 25 - July 1*
  - Objective: Develop Basic Task and Event Management Features
  - Task 1: Create migrations and models for tasks and events
  - Task 2: Implement basic CRUD operations for tasks and events
  - Task 3: Develop basic UI for task and event management
    - Basic design

- [ ] *Week 2: July 2 - July 12*
  - Objective: Google Calendar Integration and Subtasks
  - Task 1: Integrate Google Calendar API
  - Task 2: Create migrations and models for subtasks
  - Task 3: Implement CRUD.

- [ ] *Week 3: July 12 - July 18*
  - Objective: UI/UX Enhancements
  - Task 1: Enhance the UI/UX
  

- [ ] *Week 4: July 18 - July 22*
  - Objective: Testing and Refinement
  - Task 1: Further testing and bug fixing + additional feature work if possible

- [ ] *Week 5: July 23 - July 25*
  - Objective: Prepare for First Milestone Review (July 26)
  - Task 1: Finalize features and bug fixes
  - Task 2: Prepare presentation and documentation
